"""
CAG pipeline state definition for LangGraph.
All nodes read from and write to this shared typed state.
"""
import operator
from typing import Annotated, List, Optional, TypeAlias, TypedDict

from langchain_core.messages import AnyMessage


class CAGState(TypedDict):
    """
    Shared state for the optimized CAG pipeline.
    """
    messages: Annotated[list[AnyMessage], operator.add]
    query: str
    conversation_id: str
    intent: Optional[str]
    # Multi-axis scoring (Coexist with intent enum). 0-1 each.
    # Drives prompt assembly without changing routing — see _generate_node.
    intent_scores: Optional[dict]
    error: Optional[str]
    # Legacy source list consumed by generate_node/eval paths.
    retrieved_context: Optional[List[dict]]
    # Standalone query generated by rewrite_node (if applicable)
    rewritten_query: Optional[str]
    # Query actually sent to retrieval; may differ from rewritten_query when
    # safety escalation is detected (the LLM-supplied safety_preserved_query
    # retains context that the rewrite may have stripped).
    retrieval_query: Optional[str]
    # LLM-supplied safety-anchored version of the user message; used for
    # retrieval when needs_safety_escalation >= 0.5. Empty otherwise.
    # Persisted for observability (agent_logs) so we can audit what the KB
    # actually saw.
    safety_preserved_query: Optional[str]
    conversation_summary: Optional[str]  # Sprint 2 — short-term session summary
    user_profile: Optional[dict]         # Sprint 3 — long-term user memory
    user_preferences: Optional[dict]     # Sprint 4 — persistent user preferences from SQL
    # Live Moodle profile (firstname + custom fields: dept/location/position/
    # grade/point) from the JWT. Read by generate_node to greet by name and
    # contextualize answers. Per-user, never cached cross-user.
    user_context: Optional[dict]
    # Legacy embedding fields kept for old logs/tests. CAG chat no longer
    # computes retrieval embeddings on the hot path.
    query_embedding: Optional[List[float]]
    query_embedding_text: Optional[str]
    # Legacy retrieval telemetry kept for old logs/tests.
    pool_max_dense: Optional[float]
    pool_max_sparse: Optional[float]
    dense_retrieval_ok: Optional[bool]
    # Socratic coaching toggle (set from ChatRequest.coaching_mode). When True,
    # _pre_processor promotes a diagnostic/reasoning KNOWLEDGE turn to COACHING,
    # which routes to the Socratic prompt in generate_node (one grounded guiding
    # question first, light loop, then confirm + teach at wrap-up). Pure factual
    # lookups stay direct.
    coaching_mode: Optional[bool]
    # Semantic-gate telemetry (Jun 2026). The GateScore returned by
    # classify_semantic_with_scores — chat.py reads this and writes the
    # individual fields to agent_logs.gate_* so the calibration harness and
    # dashboard can plot cosine distributions and detect drift. Optional
    # because not every intent path populates it (e.g. cached turns skip
    # the pre-processor entirely).
    gate_score: Optional[dict]
    # Section drilldown (Jun 2026): when the user asks "what's inside topic X",
    # `_pre_processor` resolves the section name (via token match against
    # `section_map` OR deictic resolution against conversation history) and
    # stores the canonical section name here. `_generate_node` reads this to
    # inject `<section_materials>` with the FULL canonical item list — fully
    # dynamic, no KB dependency. `drilldown_resolution` records the path used
    # ("query" | "history" | "history_ordinal") for observability.
    drilldown_section: Optional[str]
    drilldown_resolution: Optional[str]
    # Legacy decomposition field kept for old logs/tests.
    rewritten_queries: Optional[List[str]]
    seen_chunk_ids: Optional[List[str]]
    off_scope_detected: Optional[bool]


RAGState: TypeAlias = CAGState

